### PR TITLE
Quick pass on formatting, edits, and additions.

### PR DESCRIPTION
**Pull request by maxbridges**
@imvijay2007 @vijayaustin I took a look at these instructions and made some changes. Let me know what you think. Feel free to edit my edits, too.

### CODE REVIEW

**Comment by imvijay2007** [comment]
@maxbridges Changes look good to me. Just had a merge conflict but I just went ahead & fixed it. Can we merge this?

**Comment by maxbridges** [comment]
@imvijay2007 That looks good.

**Comment by maxbridges** [comment]
@imvijay2007 Is this ready to merge yet? I don't have write access myself.

**Comment by imvijay2007** [comment]
@maxbridges Yes, merged it. I'll provide the write access as well.

**Pull request merged**
